/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/slide_icon.ttf
///
///
///

import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFamNavDrawer = 'nav_drawer';
  static const _kFontFamSlide = 'slide_icon';
  static const _kFlutterIconFamSlide = 'FlutterIcon';
  static const _kFontPkg = null;

  static const IconData navigation_drawer =
      IconData(0xe800, fontFamily: _kFontFamNavDrawer, fontPackage: _kFontPkg);
  static const IconData slide_icon =
      IconData(0xe801, fontFamily: _kFontFamSlide, fontPackage: _kFontPkg);
  static const IconData threedee_rotation = IconData(0xe800,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData ac_unit = IconData(0xe801,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData access_alarm = IconData(0xe802,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData access_alarms = IconData(0xe803,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData access_time = IconData(0xe804,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData accessibility = IconData(0xe805,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData accessible = IconData(0xe806,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData account_balance = IconData(0xe807,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData account_box = IconData(0xe808,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData account_circle = IconData(0xe809,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData adb = IconData(0xe80a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe80b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_a_photo = IconData(0xe80c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_alarm = IconData(0xe80d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_alert = IconData(0xe80e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_box = IconData(0xe80f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe810,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe811,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_location = IconData(0xe812,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart = IconData(0xe813,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_to_photos = IconData(0xe814,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData add_to_queue = IconData(0xe815,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData adjust = IconData(0xe816,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_flat = IconData(0xe817,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_flat_angled = IconData(0xe818,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_individual_suite = IconData(0xe819,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_legroom_extra = IconData(0xe81a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_legroom_normal = IconData(0xe81b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_legroom_reduced = IconData(0xe81c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_recline_extra = IconData(0xe81d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airline_seat_recline_normal = IconData(0xe81e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airplanemode_active = IconData(0xe81f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airplanemode_inactive = IconData(0xe820,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airplay = IconData(0xe821,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData airport_shuttle = IconData(0xe822,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData alarm = IconData(0xe823,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData alarm_add = IconData(0xe824,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData alarm_off = IconData(0xe825,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData alarm_on = IconData(0xe826,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData album = IconData(0xe827,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData all_inclusive = IconData(0xe828,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData all_out = IconData(0xe829,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe82a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData announcement = IconData(0xe82b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe82c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xe82d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData arrow_back = IconData(0xe82e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData arrow_downward = IconData(0xe82f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData arrow_drop_down = IconData(0xe830,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData arrow_drop_down_circle = IconData(0xe831,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData arrow_drop_up = IconData(0xe832,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData arrow_forward = IconData(0xe833,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData arrow_upward = IconData(0xe834,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData art_track = IconData(0xe835,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData aspect_ratio = IconData(0xe836,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assessment = IconData(0xe837,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assignment = IconData(0xe838,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assignment_ind = IconData(0xe839,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assignment_late = IconData(0xe83a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assignment_return = IconData(0xe83b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assignment_returned = IconData(0xe83c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assignment_turned_in = IconData(0xe83d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assistant = IconData(0xe83e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData assistant_photo = IconData(0xe83f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData attach_file = IconData(0xe840,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData attach_money = IconData(0xe841,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData attachment = IconData(0xe842,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData audiotrack = IconData(0xe843,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData autorenew = IconData(0xe844,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData av_timer = IconData(0xe845,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData backspace = IconData(0xe846,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData backup = IconData(0xe847,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData battery_alert = IconData(0xe848,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData battery_charging_full = IconData(0xe849,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData battery_full = IconData(0xe84a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData battery_std = IconData(0xe84b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData battery_unknown = IconData(0xe84c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData beach_access = IconData(0xe84d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData beenhere = IconData(0xe84e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe84f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bluetooth = IconData(0xe850,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bluetooth_audio = IconData(0xe851,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bluetooth_connected = IconData(0xe852,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bluetooth_disabled = IconData(0xe853,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bluetooth_searching = IconData(0xe854,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData blur_circular = IconData(0xe855,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData blur_linear = IconData(0xe856,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData blur_off = IconData(0xe857,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData blur_on = IconData(0xe858,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe859,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe85a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bookmark_border = IconData(0xe85b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_all = IconData(0xe85c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_bottom = IconData(0xe85d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_clear = IconData(0xe85e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_color = IconData(0xe85f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_horizontal = IconData(0xe860,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_inner = IconData(0xe861,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_left = IconData(0xe862,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_outer = IconData(0xe863,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_right = IconData(0xe864,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_style = IconData(0xe865,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_top = IconData(0xe866,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData border_vertical = IconData(0xe867,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData branding_watermark = IconData(0xe868,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_1 = IconData(0xe869,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_2 = IconData(0xe86a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_3 = IconData(0xe86b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_4 = IconData(0xe86c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_5 = IconData(0xe86d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_6 = IconData(0xe86e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_7 = IconData(0xe86f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_auto = IconData(0xe870,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_high = IconData(0xe871,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_low = IconData(0xe872,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brightness_medium = IconData(0xe873,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData broken_image = IconData(0xe874,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe875,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bubble_chart = IconData(0xe876,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData bug_report = IconData(0xe877,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData build = IconData(0xe878,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData burst_mode = IconData(0xe879,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe87a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData business_center = IconData(0xe87b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cached = IconData(0xe87c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cake = IconData(0xe87d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe87e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_end = IconData(0xe87f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_made = IconData(0xe880,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_merge = IconData(0xe881,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_missed = IconData(0xe882,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_missed_outgoing = IconData(0xe883,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_received = IconData(0xe884,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_split = IconData(0xe885,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData call_to_action = IconData(0xe886,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe887,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData camera_alt = IconData(0xe888,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData camera_enhance = IconData(0xe889,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData camera_front = IconData(0xe88a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData camera_rear = IconData(0xe88b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData camera_roll = IconData(0xe88c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe88d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData card_giftcard = IconData(0xe88e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData card_membership = IconData(0xe88f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData card_travel = IconData(0xe890,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData casino = IconData(0xe891,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cast = IconData(0xe892,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cast_connected = IconData(0xe893,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData center_focus_strong = IconData(0xe894,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData center_focus_weak = IconData(0xe895,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData change_history = IconData(0xe896,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe897,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData chat_bubble = IconData(0xe898,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData chat_bubble_outline = IconData(0xe899,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe89a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData check_box = IconData(0xe89b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData check_box_outline_blank = IconData(0xe89c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe89d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe89e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe89f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData child_care = IconData(0xe8a0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData child_friendly = IconData(0xe8a1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData chrome_reader_mode = IconData(0xe8a2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData class_icon = IconData(0xe8a3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe8a4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData clear_all = IconData(0xe8a5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe8a6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData closed_caption = IconData(0xe8a7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe8a8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cloud_circle = IconData(0xe8a9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cloud_done = IconData(0xe8aa,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cloud_download = IconData(0xe8ab,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cloud_off = IconData(0xe8ac,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cloud_queue = IconData(0xe8ad,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData cloud_upload = IconData(0xe8ae,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe8af,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData collections = IconData(0xe8b0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData collections_bookmark = IconData(0xe8b1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData color_lens = IconData(0xe8b2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData colorize = IconData(0xe8b3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe8b4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData compare = IconData(0xe8b5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData compare_arrows = IconData(0xe8b6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData computer = IconData(0xe8b7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData confirmation_number = IconData(0xe8b8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData contact_mail = IconData(0xe8b9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData contact_phone = IconData(0xe8ba,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData contacts = IconData(0xe8bb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData content_copy = IconData(0xe8bc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData content_cut = IconData(0xe8bd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData content_paste = IconData(0xe8be,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData control_point = IconData(0xe8bf,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData control_point_duplicate = IconData(0xe8c0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData copyright = IconData(0xe8c1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData create = IconData(0xe8c2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData create_new_folder = IconData(0xe8c3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe8c4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop = IconData(0xe8c5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_16_9 = IconData(0xe8c6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_3_2 = IconData(0xe8c7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_5_4 = IconData(0xe8c8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_7_5 = IconData(0xe8c9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_din = IconData(0xe8ca,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_free = IconData(0xe8cb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_landscape = IconData(0xe8cc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_original = IconData(0xe8cd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_portrait = IconData(0xe8ce,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_rotate = IconData(0xe8cf,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData crop_square = IconData(0xe8d0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe8d1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData data_usage = IconData(0xe8d2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData date_range = IconData(0xe8d3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData dehaze = IconData(0xe8d4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe8d5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData delete_forever = IconData(0xe8d6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData delete_sweep = IconData(0xe8d7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData description = IconData(0xe8d8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData desktop_mac = IconData(0xe8d9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData desktop_windows = IconData(0xe8da,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData details = IconData(0xe8db,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData developer_board = IconData(0xe8dc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData developer_mode = IconData(0xe8dd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData device_hub = IconData(0xe8de,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData devices = IconData(0xe8df,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData devices_other = IconData(0xe8e0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData dialer_sip = IconData(0xe8e1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData dialpad = IconData(0xe8e2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions = IconData(0xe8e3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_bike = IconData(0xe8e4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_boat = IconData(0xe8e5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_bus = IconData(0xe8e6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_car = IconData(0xe8e7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_railway = IconData(0xe8e8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_run = IconData(0xe8e9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_subway = IconData(0xe8ea,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_transit = IconData(0xe8eb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData directions_walk = IconData(0xe8ec,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData disc_full = IconData(0xe8ed,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData dns = IconData(0xe8ee,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData do_not_disturb = IconData(0xe8ef,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData do_not_disturb_alt = IconData(0xe8f0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData do_not_disturb_off = IconData(0xe8f1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData do_not_disturb_on = IconData(0xe8f2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData dock = IconData(0xe8f3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData domain = IconData(0xe8f4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe8f5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData done_all = IconData(0xe8f6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData donut_large = IconData(0xe8f7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData donut_small = IconData(0xe8f8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData drafts = IconData(0xe8f9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData drag_handle = IconData(0xe8fa,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData drive_eta = IconData(0xe8fb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData dvr = IconData(0xe8fc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe8fd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData edit_location = IconData(0xe8fe,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData eject = IconData(0xe8ff,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe900,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData enhanced_encryption = IconData(0xe901,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData equalizer = IconData(0xe902,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe903,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData error_outline = IconData(0xe904,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData euro_symbol = IconData(0xe905,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData ev_station = IconData(0xe906,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe907,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData event_available = IconData(0xe908,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData event_busy = IconData(0xe909,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData event_note = IconData(0xe90a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData event_seat = IconData(0xe90b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData exit_to_app = IconData(0xe90c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData expand_less = IconData(0xe90d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData expand_more = IconData(0xe90e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData explicit = IconData(0xe90f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData explore = IconData(0xe910,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData exposure = IconData(0xe911,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData exposure_neg_1 = IconData(0xe912,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData exposure_neg_2 = IconData(0xe913,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData exposure_plus_1 = IconData(0xe914,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData exposure_plus_2 = IconData(0xe915,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData exposure_zero = IconData(0xe916,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData extension = IconData(0xe917,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData face = IconData(0xe918,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xe919,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fast_rewind = IconData(0xe91a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe91b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData favorite_border = IconData(0xe91c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData featured_play_list = IconData(0xe91d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData featured_video = IconData(0xe91e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe91f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fiber_dvr = IconData(0xe920,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fiber_manual_record = IconData(0xe921,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fiber_new = IconData(0xe922,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fiber_pin = IconData(0xe923,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fiber_smart_record = IconData(0xe924,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData file_download = IconData(0xe925,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData file_upload = IconData(0xe926,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe927,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_1 = IconData(0xe928,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_2 = IconData(0xe929,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_3 = IconData(0xe92a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_4 = IconData(0xe92b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_5 = IconData(0xe92c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_6 = IconData(0xe92d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_7 = IconData(0xe92e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_8 = IconData(0xe92f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_9 = IconData(0xe930,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_9_plus = IconData(0xe931,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_b_and_w = IconData(0xe932,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_center_focus = IconData(0xe933,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_drama = IconData(0xe934,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_frames = IconData(0xe935,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_hdr = IconData(0xe936,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_list = IconData(0xe937,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_none = IconData(0xe938,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_tilt_shift = IconData(0xe939,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData filter_vintage = IconData(0xe93a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData find_in_page = IconData(0xe93b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData find_replace = IconData(0xe93c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xe93d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData first_page = IconData(0xe93e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fitness_center = IconData(0xe93f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe940,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flare = IconData(0xe941,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flash_auto = IconData(0xe942,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flash_off = IconData(0xe943,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flash_on = IconData(0xe944,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flight = IconData(0xe945,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flight_land = IconData(0xe946,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flight_takeoff = IconData(0xe947,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flip = IconData(0xe948,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flip_to_back = IconData(0xe949,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData flip_to_front = IconData(0xe94a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe94b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData folder_open = IconData(0xe94c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData folder_shared = IconData(0xe94d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData folder_special = IconData(0xe94e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData font_download = IconData(0xe94f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_align_center = IconData(0xe950,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_align_justify = IconData(0xe951,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_align_left = IconData(0xe952,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_align_right = IconData(0xe953,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_bold = IconData(0xe954,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_clear = IconData(0xe955,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_color_fill = IconData(0xe956,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_color_reset = IconData(0xe957,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_color_text = IconData(0xe958,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_indent_decrease = IconData(0xe959,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_indent_increase = IconData(0xe95a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_italic = IconData(0xe95b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_line_spacing = IconData(0xe95c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_list_bulleted = IconData(0xe95d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_list_numbered = IconData(0xe95e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_paint = IconData(0xe95f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_quote = IconData(0xe960,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_shapes = IconData(0xe961,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_size = IconData(0xe962,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_strikethrough = IconData(0xe963,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_textdirection_l_to_r = IconData(0xe964,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_textdirection_r_to_l = IconData(0xe965,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData format_underlined = IconData(0xe966,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData forum = IconData(0xe967,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe968,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData forward_10 = IconData(0xe969,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData forward_30 = IconData(0xe96a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData forward_5 = IconData(0xe96b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData free_breakfast = IconData(0xe96c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fullscreen = IconData(0xe96d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData fullscreen_exit = IconData(0xe96e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData functions = IconData(0xe96f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData g_translate = IconData(0xe970,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gamepad = IconData(0xe971,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData games = IconData(0xe972,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gavel = IconData(0xe973,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gesture = IconData(0xe974,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData get_app = IconData(0xe975,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gif = IconData(0xe976,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData goat = IconData(0xe977,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData golf_course = IconData(0xe978,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gps_fixed = IconData(0xe979,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gps_not_fixed = IconData(0xe97a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gps_off = IconData(0xe97b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData grade = IconData(0xe97c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData gradient = IconData(0xe97d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData grain = IconData(0xe97e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData graphic_eq = IconData(0xe97f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData grid_off = IconData(0xe980,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData grid_on = IconData(0xe981,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe982,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData group_add = IconData(0xe983,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData group_work = IconData(0xe984,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hd = IconData(0xe985,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hdr_off = IconData(0xe986,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hdr_on = IconData(0xe987,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hdr_strong = IconData(0xe988,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hdr_weak = IconData(0xe989,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData headset = IconData(0xe98a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData headset_mic = IconData(0xe98b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData healing = IconData(0xe98c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hearing = IconData(0xe98d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe98e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData help_outline = IconData(0xe98f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData high_quality = IconData(0xe990,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData highlight = IconData(0xe991,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData highlight_off = IconData(0xe992,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe993,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe994,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hot_tub = IconData(0xe995,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hotel = IconData(0xe996,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hourglass_empty = IconData(0xe997,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData hourglass_full = IconData(0xe998,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData http = IconData(0xe999,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData https = IconData(0xe99a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe99b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData image_aspect_ratio = IconData(0xe99c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData import_contacts = IconData(0xe99d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData import_export = IconData(0xe99e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData important_devices = IconData(0xe99f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xe9a0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData indeterminate_check_box = IconData(0xe9a1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe9a2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData info_outline = IconData(0xe9a3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData input = IconData(0xe9a4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData insert_chart = IconData(0xe9a5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData insert_comment = IconData(0xe9a6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData insert_drive_file = IconData(0xe9a7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData insert_emoticon = IconData(0xe9a8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData insert_invitation = IconData(0xe9a9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData insert_link = IconData(0xe9aa,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData insert_photo = IconData(0xe9ab,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData invert_colors = IconData(0xe9ac,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData invert_colors_off = IconData(0xe9ad,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData iso = IconData(0xe9ae,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard = IconData(0xe9af,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_down = IconData(0xe9b0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_left = IconData(0xe9b1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_right = IconData(0xe9b2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_up = IconData(0xe9b3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_backspace = IconData(0xe9b4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_capslock = IconData(0xe9b5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_hide = IconData(0xe9b6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_return = IconData(0xe9b7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_tab = IconData(0xe9b8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData keyboard_voice = IconData(0xe9b9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData kitchen = IconData(0xe9ba,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData label = IconData(0xe9bb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData label_outline = IconData(0xe9bc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData landscape = IconData(0xe9bd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe9be,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData laptop = IconData(0xe9bf,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData laptop_chromebook = IconData(0xe9c0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData laptop_mac = IconData(0xe9c1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData laptop_windows = IconData(0xe9c2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData last_page = IconData(0xe9c3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData launch = IconData(0xe9c4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData layers = IconData(0xe9c5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData layers_clear = IconData(0xe9c6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData leak_add = IconData(0xe9c7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData leak_remove = IconData(0xe9c8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData lens = IconData(0xe9c9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData library_add = IconData(0xe9ca,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData library_books = IconData(0xe9cb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData library_music = IconData(0xe9cc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData lightbulb_outline = IconData(0xe9cd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData line_style = IconData(0xe9ce,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData line_weight = IconData(0xe9cf,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData linear_scale = IconData(0xe9d0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe9d1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData linked_camera = IconData(0xe9d2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe9d3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData live_help = IconData(0xe9d4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData live_tv = IconData(0xe9d5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_activity = IconData(0xe9d6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_airport = IconData(0xe9d7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_atm = IconData(0xe9d8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_bar = IconData(0xe9d9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_cafe = IconData(0xe9da,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_car_wash = IconData(0xe9db,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_convenience_store = IconData(0xe9dc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_dining = IconData(0xe9dd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_drink = IconData(0xe9de,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_florist = IconData(0xe9df,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_gas_station = IconData(0xe9e0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_grocery_store = IconData(0xe9e1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_hospital = IconData(0xe9e2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_hotel = IconData(0xe9e3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_laundry_service = IconData(0xe9e4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_library = IconData(0xe9e5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_mall = IconData(0xe9e6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_movies = IconData(0xe9e7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_offer = IconData(0xe9e8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_parking = IconData(0xe9e9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_pharmacy = IconData(0xe9ea,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_phone = IconData(0xe9eb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_pizza = IconData(0xe9ec,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_play = IconData(0xe9ed,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_post_office = IconData(0xe9ee,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_printshop = IconData(0xe9ef,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_see = IconData(0xe9f0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_shipping = IconData(0xe9f1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData local_taxi = IconData(0xe9f2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData location_city = IconData(0xe9f3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData location_disabled = IconData(0xe9f4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData location_off = IconData(0xe9f5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData location_on = IconData(0xe9f6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData location_searching = IconData(0xe9f7,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe9f8,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe9f9,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData lock_outline = IconData(0xe9fa,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData looks = IconData(0xe9fb,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData looks_3 = IconData(0xe9fc,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData looks_4 = IconData(0xe9fd,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData looks_5 = IconData(0xe9fe,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData looks_6 = IconData(0xe9ff,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData looks_one = IconData(0xea00,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData looks_two = IconData(0xea01,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData loop = IconData(0xea02,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData loupe = IconData(0xea03,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData low_priority = IconData(0xea04,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData loyalty = IconData(0xea05,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xea06,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mail_outline = IconData(0xea07,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xea08,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData markunread = IconData(0xea09,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData markunread_mailbox = IconData(0xea0a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData memory = IconData(0xea0b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xea0c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData merge_type = IconData(0xea0d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xea0e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xea0f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mic_none = IconData(0xea10,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mic_off = IconData(0xea11,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mms = IconData(0xea12,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mode_comment = IconData(0xea13,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mode_edit = IconData(0xea14,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData monetization_on = IconData(0xea15,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData money_off = IconData(0xea16,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData monochrome_photos = IconData(0xea17,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mood = IconData(0xea18,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mood_bad = IconData(0xea19,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xea1a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData more_horiz = IconData(0xea1b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData more_vert = IconData(0xea1c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xea1d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData mouse = IconData(0xea1e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData move_to_inbox = IconData(0xea1f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xea20,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData movie_creation = IconData(0xea21,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData movie_filter = IconData(0xea22,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData multiline_chart = IconData(0xea23,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData music_note = IconData(0xea24,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData music_video = IconData(0xea25,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData my_location = IconData(0xea26,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData nature = IconData(0xea27,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData nature_people = IconData(0xea28,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData navigate_before = IconData(0xea29,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData navigate_next = IconData(0xea2a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData navigation = IconData(0xea2b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData near_me = IconData(0xea2c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData network_cell = IconData(0xea2d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData network_check = IconData(0xea2e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData network_locked = IconData(0xea2f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData network_wifi = IconData(0xea30,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData new_releases = IconData(0xea31,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData next_week = IconData(0xea32,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData nfc = IconData(0xea33,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData no_encryption = IconData(0xea34,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData no_sim = IconData(0xea35,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData not_interested = IconData(0xea36,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xea37,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData note_add = IconData(0xea38,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xea39,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData notifications_active = IconData(0xea3a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData notifications_none = IconData(0xea3b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData notifications_off = IconData(0xea3c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData notifications_paused = IconData(0xea3d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData offline_pin = IconData(0xea3e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData ondemand_video = IconData(0xea3f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData opacity = IconData(0xea40,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData open_in_browser = IconData(0xea41,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData open_in_new = IconData(0xea42,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData open_with = IconData(0xea43,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pages = IconData(0xea44,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pageview = IconData(0xea45,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData palette = IconData(0xea46,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pan_tool = IconData(0xea47,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData panorama = IconData(0xea48,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData panorama_fish_eye = IconData(0xea49,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData panorama_horizontal = IconData(0xea4a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData panorama_vertical = IconData(0xea4b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData panorama_wide_angle = IconData(0xea4c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData party_mode = IconData(0xea4d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xea4e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pause_circle_filled = IconData(0xea4f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pause_circle_outline = IconData(0xea50,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData payment = IconData(0xea51,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xea52,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData people_outline = IconData(0xea53,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_camera_mic = IconData(0xea54,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_contact_calendar = IconData(0xea55,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_data_setting = IconData(0xea56,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_device_information = IconData(0xea57,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_identity = IconData(0xea58,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_media = IconData(0xea59,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_phone_msg = IconData(0xea5a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData perm_scan_wifi = IconData(0xea5b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xea5c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData person_add = IconData(0xea5d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData person_outline = IconData(0xea5e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData person_pin = IconData(0xea5f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData person_pin_circle = IconData(0xea60,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData personal_video = IconData(0xea61,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pets = IconData(0xea62,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xea63,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_android = IconData(0xea64,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_bluetooth_speaker = IconData(0xea65,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_forwarded = IconData(0xea66,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_in_talk = IconData(0xea67,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_iphone = IconData(0xea68,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_locked = IconData(0xea69,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_missed = IconData(0xea6a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phone_paused = IconData(0xea6b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phonelink = IconData(0xea6c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phonelink_erase = IconData(0xea6d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phonelink_lock = IconData(0xea6e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phonelink_off = IconData(0xea6f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phonelink_ring = IconData(0xea70,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData phonelink_setup = IconData(0xea71,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xea72,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo_album = IconData(0xea73,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo_camera = IconData(0xea74,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo_filter = IconData(0xea75,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo_library = IconData(0xea76,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo_size_select_actual = IconData(0xea77,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo_size_select_large = IconData(0xea78,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData photo_size_select_small = IconData(0xea79,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData picture_as_pdf = IconData(0xea7a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData picture_in_picture = IconData(0xea7b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData picture_in_picture_alt = IconData(0xea7c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pie_chart = IconData(0xea7d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pie_chart_outlined = IconData(0xea7e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pin_drop = IconData(0xea7f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData place = IconData(0xea80,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData play_arrow = IconData(0xea81,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData play_circle_filled = IconData(0xea82,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData play_circle_outline = IconData(0xea83,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData play_for_work = IconData(0xea84,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData playlist_add = IconData(0xea85,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData playlist_add_check = IconData(0xea86,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData playlist_play = IconData(0xea87,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData plus_one = IconData(0xea88,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData poll = IconData(0xea89,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData polymer = IconData(0xea8a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pool = IconData(0xea8b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData portable_wifi_off = IconData(0xea8c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData portrait = IconData(0xea8d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xea8e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData power_input = IconData(0xea8f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData power_settings_new = IconData(0xea90,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData pregnant_woman = IconData(0xea91,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData present_to_all = IconData(0xea92,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xea93,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData priority_high = IconData(0xea94,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData public = IconData(0xea95,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData publish = IconData(0xea96,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData query_builder = IconData(0xea97,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData question_answer = IconData(0xea98,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData queue = IconData(0xea99,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData queue_music = IconData(0xea9a,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData queue_play_next = IconData(0xea9b,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData radio = IconData(0xea9c,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData radio_button_checked = IconData(0xea9d,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData radio_button_unchecked = IconData(0xea9e,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData rate_review = IconData(0xea9f,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xeaa0,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData recent_actors = IconData(0xeaa1,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData record_voice_over = IconData(0xeaa2,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData redeem = IconData(0xeaa3,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xeaa4,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xeaa5,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData remove = IconData(0xeaa6,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
  static const IconData account_balance_wallet = IconData(0xf008,
      fontFamily: _kFlutterIconFamSlide, fontPackage: _kFontPkg);
}
